allow start a leetcode problem with identifier, by start -i identifier

diff --git a/leetcode-scripts/start b/leetcode-scripts/start
--- a/leetcode-scripts/start
+++ b/leetcode-scripts/start
@@ -1,4 +1,40 @@
-#!/bin/sh
+#!/bin/bash
+
+identifier=""
+
+while getopts ":i:" opt; do
+  case $opt in
+    i) identifier="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    exit 1
+    ;;
+  esac
+done
+
+
+if [ "$identifier" != "" ]
+then
+	name="$(python ../main.py --subject leetcode -c get_name -i "$identifier")"
+	if [[ "$name" == "##_not_exist_##" ]]
+	then
+		echo "$identifier does not exist!"
+		exit 1
+	fi
+
+	yesno="$(echo -e "yes\nno" | fzf --prompt "Start to study $identifier. $name? ")"
+
+	if [[ "$yesno" == "yes" ]]
+	then
+		PATHTOCODE="$(python ../main.py --subject leetcode -c get_file -i "$identifier" --postfix "code.py")"
+
+		python ../main.py --subject leetcode -c start -i "$identifier" \
+			&& echo "Start coding $identifier. $name at $PATHTOCODE" \
+			&& neovide "$PATHTOCODE"
+	fi
+
+	exit 0
+fi
 
 tag="$(echo -e "$(python ../main.py --subject leetcode -c list_tag --states new,studied)" | fzf | awk -F ':' '{print $1}')"
 # if [[ "$tag" == "" ]]
